### ISSUE TITLE
Fails to build on Node 0.10

### ISSUE THREAD

**Issue by allanca** [yfinkelstein/node-zookeeper#85]
This is related to #67. I hope to get a pull request over relatively soon if someone doesn't beat me to it.

  TOUCH Release/obj.target/libzk.stamp
  CXX(target) Release/obj.target/zookeeper/src/node-zk.o
../src/node-zk.cpp:254:27: error: ‘EV_P_’ has not been declared
../src/node-zk.cpp:254:39: error: expected ‘,’ or ‘...’ before ‘_’ token
../src/node-zk.cpp:265:30: error: ‘EV_P_’ has not been declared
../src/node-zk.cpp:265:45: error: expected ‘,’ or ‘...’ before ‘_’ token
../src/node-zk.cpp:806:5: error: ‘ev_io’ does not name a type
../src/node-zk.cpp:807:5: error: ‘ev_timer’ does not name a type
../src/node-zk.cpp:811:5: error: ‘ev_tstamp’ does not name a type
../src/node-zk.cpp: In member function ‘void zk::ZooKeeper::yield()’:
../src/node-zk.cpp:208:9: error: ‘last_activity’ was not declared in this scope
../src/node-zk.cpp:208:52: error: ‘uv_loop_t’ has no member named ‘ev’
../src/node-zk.cpp:208:54: error: ‘ev_now’ was not declared in this scope
../src/node-zk.cpp:220:30: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:220:35: error: ‘ev_is_active’ was not declared in this scope
../src/node-zk.cpp:221:25: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:221:46: error: ‘ev_io_stop’ was not declared in this scope
../src/node-zk.cpp:229:51: error: ‘EV_READ’ was not declared in this scope
../src/node-zk.cpp:229:96: error: ‘EV_WRITE’ was not declared in this scope
../src/node-zk.cpp:235:28: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:235:33: error: ‘ev_is_active’ was not declared in this scope
../src/node-zk.cpp:236:23: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:236:44: error: ‘ev_io_stop’ was not declared in this scope
../src/node-zk.cpp:242:21: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:242:38: error: ‘ev_io_set’ was not declared in this scope
../src/node-zk.cpp:243:21: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:243:42: error: ‘ev_io_start’ was not declared in this scope
../src/node-zk.cpp:246:9: error: ‘zk_timer’ was not declared in this scope
../src/node-zk.cpp:247:49: error: ‘ev_timer_start’ was not declared in this scope
../src/node-zk.cpp: In static member function ‘static void zk::ZooKeeper::zk_io_cb(int)’:
../src/node-zk.cpp:256:49: error: ‘w’ was not declared in this scope
../src/node-zk.cpp:257:23: error: ‘revents’ was not declared in this scope
../src/node-zk.cpp:257:33: error: ‘EV_READ’ was not declared in this scope
../src/node-zk.cpp:257:75: error: ‘EV_WRITE’ was not declared in this scope
../src/node-zk.cpp: In static member function ‘static void zk::ZooKeeper::zk_timer_cb(int)’:
../src/node-zk.cpp:268:25: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:268:41: error: ‘ev_timer_start’ was not declared in this scope
../src/node-zk.cpp:271:49: error: ‘w’ was not declared in this scope
../src/node-zk.cpp:273:9: error: ‘ev_tstamp’ was not declared in this scope
../src/node-zk.cpp:273:19: error: expected ‘;’ before ‘now’
../src/node-zk.cpp:277:19: error: expected ‘;’ before ‘timeout’
../src/node-zk.cpp:280:13: error: ‘timeout’ was not declared in this scope
../src/node-zk.cpp:280:23: error: ‘now’ was not declared in this scope
../src/node-zk.cpp:290:44: error: expected ‘)’ before ‘w’
../src/node-zk.cpp: In member function ‘bool zk::ZooKeeper::realInit(const char_, int, clientid_t_)’:
../src/node-zk.cpp:308:19: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:308:35: error: ‘ev_init’ was not declared in this scope
../src/node-zk.cpp:309:19: error: ‘zk_timer’ was not declared in this scope
../src/node-zk.cpp:311:38: error: ‘ev_set_priority’ was not declared in this scope
../src/node-zk.cpp: In member function ‘void zk::ZooKeeper::realClose()’:
../src/node-zk.cpp:762:28: error: ‘zk_timer’ was not declared in this scope
../src/node-zk.cpp:762:36: error: ‘ev_is_active’ was not declared in this scope
../src/node-zk.cpp:763:27: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:763:51: error: ‘ev_timer_stop’ was not declared in this scope
../src/node-zk.cpp:772:32: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:772:37: error: ‘ev_is_active’ was not declared in this scope
../src/node-zk.cpp:773:29: error: ‘EV_DEFAULT_UC_’ was not declared in this scope
../src/node-zk.cpp:773:50: error: ‘ev_io_stop’ was not declared in this scope
../src/node-zk.cpp: In constructor ‘zk::ZooKeeper::ZooKeeper()’:
../src/node-zk.cpp:798:9: error: ‘zk_io’ was not declared in this scope
../src/node-zk.cpp:799:9: error: ‘zk_timer’ was not declared in this scope
make: **\* [Release/obj.target/zookeeper/src/node-zk.o] Error 1
make: Leaving directory `/home/allan/node_modules/zookeeper/build'
