### ISSUE TITLE
Error when build in node8.17

### ISSUE THREAD

**Issue by troygaga** [yfinkelstein/node-zookeeper#79]
build node-zookeeper fails with the following error:

../src/node-zk.cpp: In member function ‘void zk::ZooKeeper::realClose(int)’:
../src/node-zk.cpp:789: error: no matching function for call to ‘zk::ZooKeeper::DoEmit(v8::Persistentv8::String&)’
../src/node-zk.cpp:443: note: candidates are: void zk::ZooKeeper::DoEmit(v8::Handlev8::String, v8::Handlev8::Value)

I find that DoEmit method invoke has some mistake. 
789             DoEmit (on_closed);

change to :
Local<Value> v8code = Number::New(code);
this->DoEmit (on_closed, v8code);

build success.
